name: Update Blog Posts
  
on:
  issue_comment:
    types: [created, edited]
    
jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name 'NaayoungKwon'
        git config --global user.email 'kny8092@gmail.com'
        git push https://${{ secrets.GH_PAT }}@github.com/NaayoungKwon/NaayoungKwon.github.io.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python _scripts/update_blog.py
